#!/bin/sh

die() {
    printf '\033[1m%s\033[m\n' "$@"
    exit 1
}

random_palette() {
    set -f -- "$1/"*

    shift "$(shuf -i "1-$#" -n 1)"

    while [ ! -f "$1" ] && [ "$2" ]; do shift; done

    [ -f "$1" ] || die "Failed to select a random palette."

    palette=${1##*/}

    set +f
}

add_sequence() {
    seqs="$seqs]$1;$2\\";
}

make_sequences() {
    [ -f "$1/$palette" ] || die "Palette '$palette' not found"

    :> "$cache_dir/colors"

    while read -r line; do
        color="${line:=#000000}"

        printf '%s\n' "color${i:=0}=\"$line\"" >> "$cache_dir/colors"

        add_sequence "4;$i" "$color"

        [ "$i" = 0 ] && {
            # 11:  Background color
            # 17:  Highlight background Color
            # 257: Reversed cursor color
            # 258: Background color
            add_sequence "11" "$color"
            add_sequence "17" "$color"
            add_sequence "4;257" "$color"
            add_sequence "4;258" "$color"

            # Unless VTE
            # 708: Border color
            [ "$VTE_VERSION" ] || add_sequence "708" "$color"
        }

        [ "$i" = 8 ] && command -v xsetroot >/dev/null && {
            xsetroot -solid "$color"
        }

        [ "$i" = 15 ] && {
            # 10:  Foreground color
            # 12:  Cursor foreground color
            # 13:  Mouse foreground color
            # 19:  Highlight foreground Color
            # 256: Cursor color
            # 259: Foreground color

            add_sequence "10" "$color"
            add_sequence "12" "$color"
            add_sequence "13" "$color"
            add_sequence "19" "$color"
            add_sequence "4;256" "$color"
            add_sequence "4;259" "$color"
        }

        : $((i+=1))
    done < "$1/$palette"

    for tty in /dev/fd/0 /dev/pts/[0-9]*; do
        [ -w "$tty" ] && printf %b "$seqs" > "$tty" &
    done

    printf %b "$seqs" > "$cache_dir/palette"

    printf %s "$palette" > "$cache_dir/current"
}

print_palette() {
    printf 'Using palette: \033[1m%s\033[m\n\n' "$palette"

    for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
        printf '\033[48;5;%sm  \033[m  ' "$i"

        [ "$i" = 7 ] && printf '\n\n'
    done

    printf '\n\n'

    exit 0
}

args() {
    case $1 in
        l|light) mode=light ;;
        d|dark) mode=dark ;;
        r|revive) cat "$cache_dir/palette" 2>/dev/null; exit ;;
        *) printf '%s\n' "Usage: cpr d|dark|l|light|r|revive"; exit ;;
    esac


    set -- "${CPR_LIB%%/}/palettes/$mode"

    random_palette "$@"

    make_sequences "$@"

    print_palette
}

main() {
    [ -z "$CPR_LIB" ] && {
        die "CPR_LIB is not set."
    }

    [ -d "$CPR_LIB/palettes/$mode" ] || {
        die "No palettes found in \"$CPR_LIB/palettes/$mode\"."
    }

    mkdir -p "${cache_dir:=${HOME}/.cache/pal}"

    args "$@"
}

main "$@"
