#!/bin/sh

log() {
    printf '\e[1;3'$(((${#1} % 6) + 1))m%s'\e[m\n' "$1"
}

die() {
    printf '\033[1m%s\033[m\n' "$@"
    exit 1
}

random_palette() {
    set -f -- "$lib/"*
    shift "$(shuf -i "1-$#" -n 1)"
    set +f

    while [ ! -f "$1" ] && [ "$2" ]; do shift; done

    [ -f "$1" ] || random_palette

    palette="${1##*/}"
}

make_sequences() {
    [ -f "$1" ] || die "Palette '$1' not found"

    add_seq() { seqs="$seqs]$1;$2\\"; }

    i=0
    while read -r line; do
        color="${line:=#000000}"

        add_seq "4;$i" "$color"

        [ "$i" = 0 ] && {
            add_seq "11" "$color"
            add_seq "19" "$color"
            add_seq "4;232" "$color"

            [ "$VTE_VERSION" ] || add_seq "708" "$color"
        }

        [ "$i" = 8 ] && command -v xsetroot >/dev/null && {
            xsetroot -solid "$color"
        }

        [ "$i" = 15 ] && {
            add_seq "10" "$color"
            add_seq "12" "$color"
            add_seq "13" "$color"
            add_seq "4;256" "$color"
        }

        i=$((i+1))
    done < "$1"

    for tty in /dev/fd/0 /dev/pts/[0-9]*; do
        [ -w "$tty" ] && printf %b "$seqs" > "$tty" &
    done

    printf %b "$seqs" > "$CACHE_DIR/palette"
}

print_palette() {
    printf 'Using palette: \033[1m%s\033[m\n\n' "${1##*/}"

    for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
        printf '\033[48;5;%sm    \033[m' "$i"

        [ "$i" = 7 ] && printf '\n'
    done

    printf '\n\n'
}

list_palettes() {
    for p in "$lib/"*; do
        [ -f "$p" ] && {
            printf '\e[1;3'$(((${#p} % 6) + 1))m%s'\e[m\n' "${p##*/}"
        }
    done

    exit 0
}

args() {
    mode=light

    while getopts :s:ld opt; do case $opt in
        s)
            palette="$OPTARG"
        ;;
        l)
            list=1
        ;;
        d)
            mode=dark
        ;;
        ?)
            die "Usage: ${0##*/}, ${0##*/} <args>" \
                "-s palette   Select palette" \
                "-l           List palettes" \
                "-d           Set dark theme" \
                "-h           Show this information"
        ;;
    esac; done

    lib="${PAL_PATH%%/}/palettes/$mode"

    [ "$list" ] && list_palettes
    [ -z "$palette" ] && random_palette

    make_sequences "$lib/$palette"
    print_palette "$lib/$palette"
}

main() {
    [ -z "$PAL_PATH" ] && {
        die "PAL_PATH is not set."
    }

    mkdir -p "${CACHE_DIR:=${HOME}/.cache/pal}"

    args "$@"
}

main "$@"
