#!/bin/sh

log() {
    printf '\e[1;3'$(((${#1} % 6) + 1))m%s'\e[m\n' "$1"
}

die() {
    printf '\033[1m%s\033[m\n' "$@"
    exit 1
}

random_palette() {
    set -f -- "$1/"*
    shift "$(shuf -i "1-$#" -n 1)"
    set +f

    while [ ! -f "$1" ] && [ "$2" ]; do shift; done

    [ -f "$1" ] || args

    palette=${1##*/}
}

add_sequence() {
    seqs="$seqs]$1;$2\\";
}

make_sequences() {
    [ -f "$1/$palette" ] || die "Palette '$palette' not found"

    i=0
    while read -r line; do
        color="${line:=#000000}"

        add_sequence "4;$i" "$color"

        [ "$i" = 0 ] && {
            add_sequence "11" "$color"
            add_sequence "19" "$color"
            add_sequence "4;232" "$color"

            [ "$VTE_VERSION" ] || add_sequence "708" "$color"
        }

        [ "$i" = 8 ] && command -v xsetroot >/dev/null && {
            xsetroot -solid "$color"
        }

        [ "$i" = 15 ] && {
            add_sequence "10" "$color"
            add_sequence "12" "$color"
            add_sequence "13" "$color"
            add_sequence "4;256" "$color"
        }

        i=$((i+1))
    done < "$1/$palette"

    for tty in /dev/fd/0 /dev/pts/[0-9]*; do
        [ -w "$tty" ] && printf %b "$seqs" > "$tty" &
    done

    printf %b "$seqs" > "$CACHE_DIR/palette"
}

print_palette() {
    printf 'Using palette: \033[1m%s\033[m\n\n' "$palette"

    for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
        printf '\033[48;5;%sm    \033[m' "$i"

        [ "$i" = 7 ] && printf '\n'
    done

    printf '\n\n'

    exit 0
}

list_palettes() {
    for p in "$1/"*; do
        [ -f "$p" ] && {
            printf '\e[1;3'$(((${#p} % 6) + 1))m%s'\e[m\n' "${p##*/}"
        }
    done

    exit 0
}

args() {
    mode=light

    while getopts ls:dvh opt; do case $opt in
        l) list=1 ;;
        s) palette=$OPTARG ;;
        d) mode=dark ;;
        v) die "0.0.1" ;;
        *)
            die "Usage: ${0##*/}, ${0##*/} <args>" \
                "             Use a random palette (no args, or with '-d')" \
                "-s palette   Select palette" \
                "-l           List palettes" \
                "-d           Set dark theme (random or by selecting palette)" \
                "-h           Show this information"
        ;;
    esac; done

    set -- "${PAL_PATH%%/}/palettes/$mode"

    [ "$list" ] && list_palettes "$@"
    [ "$palette" ] || random_palette "$@"

    [ "$palette" ] && {
        make_sequences "$@"
        print_palette
    }
}

main() {
    [ -z "$PAL_PATH" ] && {
        die "PAL_PATH is not set."
    }

    mkdir -p "${CACHE_DIR:=${HOME}/.cache/pal}"

    args "$@"
}

main "$@"
